name: Automatic Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node
      uses: nodenv/actions-setup-nodenv@v2.0.4

    - name: Install dependencies
      run: npm i

    - name: Build project
      run: npm run build
    
    - name: Deploy
      uses: crazy-max/ghaction-github-pages@v2.0.0
      with:
        allow_empty_commit: false
        build_dir: ./build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
